name: "ESLint中文"
exclude: [
  'node_modules',
  'vendor'
]
description: "ESLint中文官网,ESLint中英文对照,JavaScript代码检测,JavaScript代码风格检测,JavaScript代码自动格式化"
url: http://cn.eslint.org
permalink: /blog/:year/:month/:title
gems:
    - jekyll-sitemap
    - jekyll-redirect-from
    - algoliasearch-jekyll
kramdown:
  input: GFM
algolia:
  application_id: 'XWXG7MEBSB'
  index_name:     'eslint'
  record_css_selector: p,li,tr,h1,h2,h3,h4,h5,h6
  settings:
    advancedSyntax: true
    highlightPostTag: </mark>
    highlightPreTag: <mark>
    minWordSizefor1Typo: 3
    minWordSizefor2Typos: 7
    attributesToIndex:
      - title
      - text
      - category,subcategory,display_title # Needed for the highlight
    attributesToHighlight:
      - category
      - subcategory
      - display_title
      - text
    customRanking:
      - desc(weight.type)
      - desc(weight.tag_name)
      - asc(weight.position)
    attributesToSnippet:
      - text:20
