name: "ESLint中文"
title: "ESLint中文"
repository: "eslint/cn.eslint.org"
exclude: [
  'node_modules',
  'bower_components',
  'vendor'
]
keywords: "ESLint中文, ESLint中文网, ESLint规则, ESLint配置, 代码检测, 代码质量, JavaScript, Linter, Linting, Pluggable, Configurable, Code Quality"
description: "ESLint中文官网, ESLint中英文对照, JavaScript代码检测, JavaScript代码风格检测, JavaScript代码自动格式化,A pluggable and configurable linter tool for identifying and reporting on patterns in JavaScript. Maintain your code quality with ease."
url: https://cn.eslint.org
permalink: /blog/:year/:month/:title
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
kramdown:
  input: GFM
  toc_levels: 2..3
